version: "3.2"
services:
  qrcode:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'images'
      QR_CODE_DEFAULT_URL: 'https://hub.docker.com/r/kaw393939/qrcode'
      QR_CODE_DEFAULT_FILE_NAME: 'docker_hub.png'
    volumes:
      - .:/home/myuser